name: Trigger auto deployment for tacit-knowledge-bot-full

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tacit-knowledge-bot-full-AutoDeployTrigger-2feb45a3-96ab-40b1-87e1-569efa16f9a6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TACITKNOWLEDGEBOTFULL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TACITKNOWLEDGEBOTFULL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TACITKNOWLEDGEBOTFULL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.TACITKNOWLEDGEBOTFULL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TACITKNOWLEDGEBOTFULL_REGISTRY_PASSWORD }}
          containerAppName: tacit-knowledge-bot-full
          resourceGroup: knowledge-bot-west
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


